# Generated by Django 6.0.5 on 2026-05-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente_nome',
            field=models.CharField(default='vazio', max_length=150, verbose_name='Nome do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.CharField(choices=[('victoria', 'Victoria'), ('adriana', 'Adriana'), ('josiane', 'Josiane'), ('rosangela', 'Rosangela'), ('camila', 'Camila')], default='vazio', max_length=50, verbose_name='Profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(default='vazio', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
