# Generated by Django 6.0.5 on 2026-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
